version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accountdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend-net
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
        
  customer-service:
    build: ./customers
    container_name: customer-service
    ports:
      - "8081:8081"
    networks:
      - backend-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/accountdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql-db:
       condition: service_healthy
      kafka:
       condition: service_healthy

  account-service:
    build: ./accounts
    container_name: account-service
    ports:
      - "8080:8080"
    networks:
      - backend-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/accountdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      CUSTOMER_SERVICE_URL: http://customer-service:8081
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
     mysql-db:
      condition: service_healthy
     kafka:
      condition: service_healthy
     customer-service: 
      condition: service_healthy

networks:
  backend-net:

volumes:
  db-data:
