version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accountdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-net

  customer-service:
    build: ./customers
    container_name: customer-service
    ports:
      - "8081:8081"
    networks:
      - backend-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/accountdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - mysql-db

  account-service:
      build: ./accounts
      container_name: account-service
      ports:
        - "8080:8080"
      networks:
        - backend-net
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/accountdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: secret
        CUSTOMER_SERVICE_URL: http://customer-service:8081
      depends_on:
        - mysql-db
        - customer-service
networks:
  backend-net:

volumes:
  db-data:


  